---
name: validate-tf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  validate-tf:
    uses: trussworks/shared-actions/.github/workflows/validate-tf.yml@637d269a81479673b19d9e7b02b98d75b1805b46 # v0.1.1
